### ISSUE TITLE
Your requirements.txt is invalid. Snapshot your logs for details.

### ISSUE THREAD

**Issue by James-Roche** [awslabs/eb-py-flask-signup#9] opened 2016-03-15 15:35 UTC
[Instance: i-0678efc54eef84544] Command failed on instance. Return code: 1 Output: (TRUNCATED)...) File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call raise CalledProcessError(retcode, cmd) CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1. Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.

Help needed, I'm new to Github and AWS :(

**Comment by Accelero** [comment] 2016-04-15 17:07
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-heb0vr_m/boto
You are using pip version 7.1.2, however version 8.1.1 is available.

**Comment by Kalaborative** [comment] 2017-09-26 19:55
I'm getting this same error, but with exit status 2. Does anyone know what the problem is? I've followed the steps directly from the AWS Docs

**Comment by haotianw465** [comment] 2017-09-28 01:39
@Kalaborative I pushed a fix for the requirement.txt at master branch. It works for me on the newest python3.4 platform (default one when you create the environment). If you're still seeing this issue please let me know which branch and platform you're using.

**Comment by Kalaborative** [comment] 2017-10-02 22:51
@haotianw465 I put this on SO and got my problem resolved. Turned out the requirements.txt file had a BOF error and had a bad encoding (not sure how tho). Saved it with ANSI encoding via Notepad and everything works. The push on master branch works well also. Thanks!

**Comment by Kalaborative** [comment] 2017-10-02 22:53
Sorry I meant BOM.. thanks!

**Closed** 2017-10-03 00:28 UTC
